// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file sample.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "sample.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>




Sample::Sample()
{
}

Sample::~Sample()
{
}

Sample::Sample(
        const Sample& x)
{
    m_index = x.m_index;
    m_key_value = x.m_key_value;
}

Sample::Sample(
        Sample&& x) noexcept
{
    m_index = x.m_index;
    m_key_value = std::move(x.m_key_value);
}

Sample& Sample::operator =(
        const Sample& x)
{

    m_index = x.m_index;
    m_key_value = x.m_key_value;
    return *this;
}

Sample& Sample::operator =(
        Sample&& x) noexcept
{

    m_index = x.m_index;
    m_key_value = std::move(x.m_key_value);
    return *this;
}

bool Sample::operator ==(
        const Sample& x) const
{
    return (m_index == x.m_index &&
           m_key_value == x.m_key_value);
}

bool Sample::operator !=(
        const Sample& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member index
 * @param _index New value for member index
 */
void Sample::index(
        int32_t _index)
{
    m_index = _index;
}

/*!
 * @brief This function returns the value of member index
 * @return Value of member index
 */
int32_t Sample::index() const
{
    return m_index;
}

/*!
 * @brief This function returns a reference to member index
 * @return Reference to member index
 */
int32_t& Sample::index()
{
    return m_index;
}


/*!
 * @brief This function copies the value in member key_value
 * @param _key_value New value to be copied in member key_value
 */
void Sample::key_value(
        const std::string& _key_value)
{
    m_key_value = _key_value;
}

/*!
 * @brief This function moves the value in member key_value
 * @param _key_value New value to be moved in member key_value
 */
void Sample::key_value(
        std::string&& _key_value)
{
    m_key_value = std::move(_key_value);
}

/*!
 * @brief This function returns a constant reference to member key_value
 * @return Constant reference to member key_value
 */
const std::string& Sample::key_value() const
{
    return m_key_value;
}

/*!
 * @brief This function returns a reference to member key_value
 * @return Reference to member key_value
 */
std::string& Sample::key_value()
{
    return m_key_value;
}


// Include auxiliary functions like for serializing/deserializing.
#include "sampleCdrAux.ipp"

